### ISSUE TITLE
Script to prepare for StereoMIS dataset

### ISSUE THREAD

**Issue by Gaozhongpai** [jinlab-imvr/Deform3DGS#1]
Hi, thanks for releasing the code. 

I have run `robust-pose-estimator` as `# python preprocess_video_data.py ../../dataset/StereoMIS` to prepare the `StereoMIS` dataset. Could you provide the additional script to convert the dataset to the same format as the `EndoNeRF` dataset. Thanks

**Comment by lala-sean** [comment]
Hi, thanks for your attention.
I added the script `stereomis2endonerf.py` to extract clips in StereoMIS dataset, estimate depth, convert the format to EndoNeRF, and rename the files accordingly. Hope this helps. Thanks

**Comment by lala-sean** [comment]
> Hi, thanks for releasing the code.
> 
> I have run `robust-pose-estimator` as `# python preprocess_video_data.py ../../dataset/StereoMIS` to prepare the `StereoMIS` dataset. Could you provide the additional script to convert the dataset to the same format as the `EndoNeRF` dataset. Thanks

Hi, thanks for your attention.
I added the script `stereomis2endonerf.py` to extract clips in StereoMIS dataset, estimate depth, convert the format following EndoNeRF, and rename the files accordingly. Hope this helps. Thanks
