### ISSUE TITLE
About the process of StereoMIS data

### ISSUE THREAD

**Issue by LiuHengyu321** [jinlab-imvr/Deform3DGS#2]
Hi @YuemingJin, @ysjue, and @lala-sean,

Thank you for your valuable work.

I am interested in the StereoMIS data used in your research, but I have a few questions regarding some details:

(1) Could you provide the exact clips used by Deform3DGS, as you mentioned in your paper "select 3 clips from video P2_7 and P3 in StereoMIS datasets"?
(2) The link for preprocessing the StereoMIS dataset, "please follow this [GitHub repo](https://github.com/aimi-lab/robust-pose-estimatot.git) to preprocess the dataset," is invalid. Would you be able to update this link?

Additionally, could the training and testing data of StereoMIS be open-sourced directly?

Thanks again!

**Comment by LiuHengyu321** [comment]
I have checked the stereomis2endonerf.py and noticed that the code for splitting the stereo video into frames is not provided.

Could you please provide the related code and the exact frames of the three clips used by Deform3DGS?

Thanks！

**Comment by lala-sean** [comment]
> Hi @YuemingJin, @ysjue, and @lala-sean,
> 
> Thank you for your valuable work.
> 
> I am interested in the StereoMIS data used in your research, but I have a few questions regarding some details:
> 
> (1) Could you provide the exact clips used by Deform3DGS, as you mentioned in your paper "select 3 clips from video P2_7 and P3 in StereoMIS datasets"? (2) The link for preprocessing the StereoMIS dataset, "please follow this [GitHub repo](https://github.com/aimi-lab/robust-pose-estimatot.git) to preprocess the dataset," is invalid. Would you be able to update this link?
> 
> Additionally, could the training and testing data of StereoMIS be open-sourced directly?
> 
> Thanks again!

Hi, thanks for your interest in our work. I have updated the link (https://github.com/aimi-lab/robust-pose-estimator). Now it should be accessible. You can follow the preprocess step in the given link to obtain the frames. After that, you can use the stereomis2endonerf.py to extract any sequences of interest from StereoMIS dataset. 

I manually identified several clips with static camera views: P2_1: [1, 247]; P3: [9100, 9467], [11000, 11400], [11200, 11525]. Please check it out!

**Comment by LiuHengyu321** [comment]
Hi @lala-sean, thank you for updating the link and providing the exact clips!
