### ISSUE TITLE
configs for the StereoMIS dataset

### ISSUE THREAD

**Issue by bingcheg** [jinlab-imvr/Deform3DGS#4]
Dear Author, 

Thanks for this excellent work. I wonder do you provide the configs for the StereoMIS dataset？

**Comment by lala-sean** [comment]
Hi, thanks for your attention. The `arguments/endonerf/default.py` works for both EndoNeRF and StereoMIS since all the StereoMIS clips in our work have been reorganized in EndoNeRF's format.
